const ideas = {
    "AI": [
        "AI-powered Study Assistant",
        "AI Resume Analyzer",
        "AI Chatbot for Mental Health Support",
        "AI-Based Personalized Learning Platform",
        "AI-Powered Code Review Tool",
        "AI-Powered Virtual Career Coach",
        "AI-Based Resume Scoring System",
        "AI for Real-Time Sign Language Translation",
        "AI-Powered Interview Preparation Assistant",
        "AI-Based Financial Advisor for Students",
        "AI-Powered Fake News Detector",
        "AI-Based Automated Recipe Generator",
        "AI-Powered Voice Cloning for Accessibility",
        "AI-Based Image Captioning Tool",
        "AI-Powered Smart Note-Taking Assistant",
        "AI-Based Real-Time Language Translator",
        "AI-Powered Podcast Summarizer",
        "AI-Based Health Risk Prediction System",
        "AI-Powered Diet Recommendation App",
        "AI-Based Music Recommendation for Mood",
        "AI-Powered Resume Builder with Suggestions",
        "AI-Powered Career Path Predictor",
        "AI-Based Time Management Assistant",
        "AI-Powered Personalized Book Recommendation",
        "AI-Powered News Summarization Tool",
        "AI-Based Personalized Fitness Trainer",
        "AI-Powered Smart Meeting Notes Generator",
        "AI-Based Chatbot for Academic Guidance",
        "AI-Powered Email Summarizer",
        "AI-Based Personalized Movie Recommendation",
        "AI-Based Code Debugging Assistant",
        "AI-Powered Virtual Science Experiment Platform",
        "AI-Based Brainstorming Partner",
        "AI-Powered Online Debate Analyzer",
        "AI-Based Online Exam Proctoring System",
        "AI-Powered Language Pronunciation Trainer",
        "AI-Based Personalized Nutrition Planner",
        "AI-Powered Adaptive Learning for Dyslexic Students",
        "AI-Based Career Skill Assessment Tool",
        "AI-Powered Job Interview Simulator",
        "AI-Based Legal Document Summarizer",
        "AI-Powered Auto-Reply System for Emails",
        "AI-Based Online Teaching Assistant",
        "AI-Powered Voice Emotion Detection",
        "AI-Based Stress Management Coach",
        "AI-Powered Smart Resume Formatting Tool",
        "AI-Based Noise Reduction for Online Meetings",
        "AI-Powered Personalized Playlist Generator",
        "AI-Based Automated Customer Service Bot",
        "AI-Powered Fact-Checking Tool for Journalists",
        "AI-Based Medical Symptom Checker",
        "AI-Powered Social Media Sentiment Analyzer",
        "AI-Based Virtual Tutor for Programming",
        "AI-Powered Smart Calendar Assistant",
        "AI-Based Voice-Controlled Task Manager",
        "AI-Powered Website Content Optimizer",
        "AI-Based Virtual Therapist for Anxiety",
        "AI-Powered Emotion-Based Music Player",
        "AI-Based Auto-Transcriber for Lectures",
        "AI-Powered Smart Traffic Management System",
        "AI-Based Weather Impact Predictor",
        "AI-Powered Chatbot for Parenting Advice",
        "AI-Based Personalized Wedding Planner",
        "AI-Powered Online Reputation Management",
        "AI-Based Gamified Learning Platform",
        "AI-Powered Automated Data Entry Assistant",
        "AI-Based Smart Document Scanner",
        "AI-Powered AI Art Generator",
        "AI-Based Personalized Study Roadmap Creator",
        "AI-Powered Travel Itinerary Generator",
        "AI-Based Automated Health Reports Analysis",
        "AI-Powered Remote Team Collaboration Assistant",
        "AI-Based Smart Virtual Business Assistant",
        "AI-Powered Smart Clothing Recommendation System",
        "AI-Based Virtual Museum Guide",
        "AI-Powered Personal Finance Planner",
        "AI-Based AI-Powered Coding Mentor",
        "AI-Powered Predictive Maintenance for Cars",
        "AI-Based Real-Time Stock Market Predictor",
        "AI-Powered Automated Podcast Creator",
        "AI-Based Virtual Reality Storytelling Assistant",
        "AI-Powered Fake Product Review Detector",
        "AI-Based Employee Productivity Tracker",
        "AI-Powered YouTube Video Summary Generator",
        "AI-Based Real-Time Speech Translator",
        "AI-Powered Personalized Workout Routine Generator",
        "AI-Based AI-Powered Mental Health Checkup Tool",
        "AI-Powered AI-Based Home Automation Assistant",
        "AI-Based Emotional Intelligence Trainer",
        "AI-Powered 3D Model Generator",
        "AI-Based Smart Presentation Builder",
        "AI-Powered Automated UX/UI Design Assistant",
        "AI-Based Personalized Content Generator for Creators",
        "AI-Powered AI-Based Dating Advice Bot",
        "AI-Based Personalized Stock Investment Guide",
        "AI-Powered AI-Powered Ethical Hacking Assistant",
        "AI-Based Automated Performance Review Analyzer",
        "AI-Powered Smart Home Energy Optimization",
        "AI-Based AI-Powered Startup Pitch Generator",
        "AI-Powered AI-Based Resume Cover Letter Writer",
        "AI-Based AI-Powered Digital Twin for Business",
        "AI-Powered AI-Based Legal Chatbot",
        "AI-Based AI-Powered Video Game Level Generator",
        "AI-Powered AI-Based Personal AI Assistant",
        "AI-Based AI-Powered Podcast Voice Enhancer",
        "AI-Powered AI-Based AI Ethics Evaluator",
        "AI-Based AI-Powered Political Bias Detector",
        "AI-Powered AI-Based Smart Farming Assistant",
        "AI-Based AI-Powered 3D Avatar Creator",
        "AI-Powered AI-Based Personalized Virtual Therapist",
        "AI-Based AI-Powered Online Privacy Protector",
        "AI-Powered AI-Based Smart Parking Assistant",
        "AI-Based AI-Powered Real-Time Virtual Interviewer",
        "AI-Powered AI-Based Automated Book Summarizer",
        "AI-Based AI-Powered Personalized Marketing Assistant",
        "AI-Powered AI-Based AI-Powered Automated Subtitles Generator",
        "AI-Based AI-Powered Student Grade Prediction System",
        "AI-Powered AI-Based AI-Powered Automated Report Writer",
        "AI-Based AI-Powered Custom Recipe Generator",
        "AI-Powered AI-Based AI-Powered Fashion Trend Predictor",
        "AI-Based AI-Powered AI-Powered Speech Therapy Assistant",
        "AI-Powered AI-Based Personalized Travel Planner"
    ],

    "Web": [
        "Personal Finance Tracker",
        "Task Manager for Students",
        "AI-Powered Resume Builder",
        "Real-Time Online Code Editor",
        "Collaborative Whiteboard for Teams",
        "Personalized News Aggregator",
        "Smart Habit Tracker",
        "AI-Powered Portfolio Website Generator",
        "Automated Meeting Scheduler",
        "AI-Based Content Summarizer",
        "Real-Time Chat Application",
        "Voice-Controlled Web Browser",
        "Crowdsourced Local Event Finder",
        "Smart Recipe Suggestion App",
        "Blockchain-Based Digital Identity Verification",
        "Minimalist Blogging Platform",
        "Virtual Study Room with Pomodoro Timer",
        "Personalized Career Roadmap Generator",
        "Online Document Collaboration Tool",
        "Custom AI-Powered Chatbot Generator",
        "Real-Time Sports Score Tracker",
        "AI-Based Job Interview Preparation Platform",
        "Decentralized Marketplace for Digital Art",
        "Online Interactive Storytelling Platform",
        "AI-Powered Resume and Cover Letter Analyzer",
        "Smart Travel Planner with Budget Tracker",
        "Automated Social Media Content Generator",
        "AI-Based Personalized Learning Portal",
        "Online Customer Support Chatbot",
        "Collaborative Task Management App",
        "Smart Budgeting Tool for Small Businesses",
        "Online Exam and Quiz Platform",
        "AI-Based Social Media Sentiment Analyzer",
        "AI-Powered Automated Website Builder",
        "Real-Time Weather Dashboard with Alerts",
        "Crowdsourced Product Review Platform",
        "Virtual Business Card Generator",
        "AI-Based Smart Email Sorting Tool",
        "Decentralized Job Board for Freelancers",
        "AI-Powered Automated Resume Ranking System",
        "Gamified Learning Platform for Kids",
        "Online Subscription Tracker",
        "Real-Time Crypto Price Tracker",
        "Online Pet Adoption Platform",
        "AI-Powered Personal Assistant Dashboard",
        "Crowdsourced Idea Validation Platform",
        "AI-Based Automated Presentation Generator",
        "Real-Time Language Translator for Websites",
        "Online Community for Book Lovers",
        "AI-Powered AI Art Generator",
        "AI-Based Automated Video Subtitle Generator",
        "Online Smart Meal Planner",
        "Web-Based Personal Health Journal",
        "AI-Powered Fake News Detection Tool",
        "Web-Based Minimalist To-Do List App",
        "AI-Powered Learning Path Generator",
        "Real-Time Traffic and Route Optimization Tool",
        "Decentralized Voting System for Online Polls",
        "Online Therapy and Mental Wellness Platform",
        "Interactive Resume Builder with Portfolio Integration",
        "Smart Home Energy Management Dashboard",
        "AI-Based Automated Social Media Post Scheduler",
        "Web-Based Gamified Workout Challenge Platform",
        "Personalized Podcast Recommendation System",
        "AI-Powered Smart Notes Organizer",
        "Web-Based Secure Digital Signature Generator",
        "AI-Based Automated Stock Market Analysis Tool",
        "Web-Based Open Source AI Model Repository",
        "Web-Based Personal AI Assistant",
        "AI-Powered Career Counseling Chatbot",
        "AI-Based Virtual Study Group Matchmaker",
        "Online Personalized Language Learning Platform",
        "AI-Powered Personal Finance Advisor",
        "Web-Based AI-Powered Search Engine",
        "Online Freelancer Skill Development Tracker",
        "AI-Based Automated Personal Blogging Platform",
        "Web-Based Real-Time Smart Meeting Minutes Generator",
        "AI-Powered Customer Feedback Analysis Tool",
        "Web-Based AI-Powered Document Translator",
        "Online Decentralized File Storage Platform",
        "AI-Powered Product Recommendation Engine",
        "Web-Based Anonymous Social Media Platform",
        "Web-Based Interactive Resume Timeline",
        "AI-Powered Web-Based Legal Document Summarizer",
        "Online Data Visualization Dashboard",
        "AI-Powered Job Skill Assessment Platform",
        "Web-Based Personalized Workout Generator",
        "Real-Time Event Ticketing and Booking System",
        "Web-Based Ethical Hacking Learning Platform",
        "AI-Powered Automated Podcast Creator",
        "Web-Based AI-Powered Smart Virtual Assistant",
        "Decentralized Web-Based Digital Rights Management System",
        "Online Crowdfunding Platform for Social Causes",
        "AI-Powered AI Chatbot for Small Businesses",
        "Web-Based AI-Powered Personal Time Management Assistant",
        "Online Personal Brand Management Dashboard",
        "Web-Based AI-Powered Market Trend Analyzer",
        "Real-Time AI-Powered Resume Feedback Tool",
        "AI-Powered Web-Based Automated Chatbot Generator",
        "Web-Based AI-Powered Personalized Investment Planner",
        "AI-Based Smart Restaurant Menu Recommendation",
        "Web-Based Decentralized Data Ownership Platform",
        "AI-Powered Web-Based Automated Resume Screening Tool",
        "Online AI-Powered Social Media Content Generator",
        "AI-Powered Web-Based Sentiment Analysis Tool",
        "Web-Based Virtual Reality-Based Travel Guide",
        "Online AI-Powered Personal Music Recommendation Engine",
        "Web-Based Smart Gardening Assistant",
        "AI-Powered Web-Based Stock Portfolio Management Tool",
        "Web-Based AI-Powered Smart Interview Coach",
        "Online Web-Based AI-Powered Smart Resume Formatter",
        "AI-Based Smart Contact Management System",
        "Web-Based AI-Powered Emotional Well-Being Tracker",
        "Web-Based Personalized Movie Recommendation System",
        "AI-Powered Web-Based Digital Portfolio Showcase",
        "Web-Based Decentralized Online Education Platform",
        "Online AI-Powered Smart Content Curation Tool",
        "AI-Powered Web-Based Freelance Work Marketplace",
        "Online Web-Based AI-Powered Smart Business Plan Generator",
        "AI-Powered Web-Based Smart Personality Assessment Tool",
        "Web-Based Interactive AI-Powered Storytelling Platform",
        "AI-Powered Web-Based Smart Employee Feedback System",
        "Web-Based AI-Powered Personalized Shopping Assistant",
        "AI-Powered Web-Based Smart Traffic Violation Detection",
        "Web-Based AI-Powered Gamified Fitness App",
        "AI-Powered Web-Based Smart Personalized Learning Assistant",
        "Online AI-Powered Web-Based Real-Time Collaborative Coding Platform",
        "Web-Based AI-Powered Personalized Meditation Assistant",
        "AI-Powered Web-Based Real-Time Smart Language Pronunciation Guide",
        "Web-Based AI-Powered Smart Study Planner",
        "AI-Powered Web-Based Smart Resume and LinkedIn Optimization Tool",
        "Web-Based AI-Powered AI Career Progression Analysis Tool",
        "Online AI-Powered Web-Based Smart Image Colorizer",
        "Web-Based AI-Powered AI-Powered Virtual Art Gallery",
        "Web-Based AI-Powered Smart Personality Development Guide",
        "Online Web-Based AI-Powered Virtual Home Designer",
        "AI-Powered Web-Based Smart Budget Allocation Tool",
        "Web-Based AI-Powered Smart Relationship Compatibility Checker",
        "Online AI-Powered Web-Based Smart Legal Assistant",
        "AI-Powered Web-Based Smart Sentiment-Based Book Recommendation System",
        "Web-Based AI-Powered Personalized Horoscope Generator",
        "Online AI-Powered Web-Based Smart Virtual Wedding Planner",
        "Web-Based AI-Powered Smart Event Planning Assistant",
        "AI-Powered Web-Based Smart Emotional Intelligence Coach",
        "Web-Based AI-Powered Smart Career Roadmap Visualization Tool",
        "AI-Powered Web-Based Smart Automated Data Entry System",
        "Online AI-Powered Web-Based Smart Team Collaboration Hub",
        "Web-Based AI-Powered Smart Nutrition Advisor",
        "Online AI-Powered Web-Based Smart Image Background Remover",
        "AI-Powered Web-Based Smart Task Automation Assistant",
        "Web-Based AI-Powered Smart Resume Video Creator",
        "Online AI-Powered Web-Based Smart Virtual Therapy Room",
        "AI-Powered Web-Based Smart Automated Book Summary Generator",
        "Web-Based AI-Powered Smart Video Editing Assistant",
        "AI-Powered Web-Based Smart AI-Powered Virtual Tutor",
        "Web-Based AI-Powered Smart Digital Art Workshop Platform",
        "AI-Powered Web-Based Smart Emotional Wellness Tracker",
        "Web-Based AI-Powered Smart Custom Avatar Creator"

    ],
    "Social": [
        "Mental Wellness App",
        "Volunteer Finder",
        "Crowdsourced Charity Finder",
        "AI-Powered Accessibility Tool for the Blind",
        "Eco-Friendly Lifestyle Tracker",
        "Social Good Project Collaboration Platform",
        "Real-Time Emergency Alert System",
        "AI-Powered Sign Language Interpreter",
        "Carbon Footprint Tracker",
        "Web-Based Mental Health Support Group",
        "Community-Based Food Waste Management System",
        "Digital Literacy Platform for Underprivileged",
        "AI-Powered Online Cyberbullying Detector",
        "Crowdsourced Blood Donation Platform",
        "Smart Donation Matching System",
        "Gamified Habit-Building for Social Impact",
        "Online Mental Health First Aid Training",
        "Women Safety Alert App",
        "Personalized Environmental Impact Report",
        "Community-Based Support Network",
        "Web-Based Personal Safety Checklist",
        "Emergency Contacts Aggregator App",
        "Local Volunteer Matchmaking Platform",
        "Community-Based Disaster Relief Platform",
        "Public Transport Efficiency Tracker",
        "AI-Powered Fake News Identification",
        "Crowdsourced Pet Adoption Platform",
        "Social Good Project Funding Platform",
        "AI-Powered Public Sentiment Analysis",
        "Online Platform for Skill-Based Volunteering"
    ],


    "all": ["Mental Wellness App",
        "Volunteer Finder",
        "Crowdsourced Charity Finder",
        "AI-Powered Accessibility Tool for the Blind",
        "Eco-Friendly Lifestyle Tracker",
        "Social Good Project Collaboration Platform",
        "Real-Time Emergency Alert System",
        "AI-Powered Sign Language Interpreter",
        "Carbon Footprint Tracker",
        "Web-Based Mental Health Support Group",
        "Community-Based Food Waste Management System",
        "Digital Literacy Platform for Underprivileged",
        "AI-Powered Online Cyberbullying Detector",
        "Crowdsourced Blood Donation Platform",
        "Smart Donation Matching System",
        "Gamified Habit-Building for Social Impact",
        "Online Mental Health First Aid Training",
        "Women Safety Alert App",
        "Personalized Environmental Impact Report",
        "Community-Based Support Network",
        "Web-Based Personal Safety Checklist",
        "Emergency Contacts Aggregator App",
        "Local Volunteer Matchmaking Platform",
        "Community-Based Disaster Relief Platform",
        "Public Transport Efficiency Tracker",
        "AI-Powered Fake News Identification",
        "Crowdsourced Pet Adoption Platform",
        "Social Good Project Funding Platform",
        "AI-Powered Public Sentiment Analysis",
        "Online Platform for Skill-Based Volunteering",

     
        "Personal Finance Tracker",
        "Task Manager for Students",
        "AI-Powered Resume Builder",
        "Real-Time Online Code Editor",
        "Collaborative Whiteboard for Teams",
        "Personalized News Aggregator",
        "Smart Habit Tracker",
        "AI-Powered Portfolio Website Generator",
        "Automated Meeting Scheduler",
        "AI-Based Content Summarizer",
        "Real-Time Chat Application",
        "Voice-Controlled Web Browser",
        "Crowdsourced Local Event Finder",
        "Smart Recipe Suggestion App",
        "Blockchain-Based Digital Identity Verification",
        "Minimalist Blogging Platform",
        "Virtual Study Room with Pomodoro Timer",
        "Personalized Career Roadmap Generator",
        "Online Document Collaboration Tool",
        "Custom AI-Powered Chatbot Generator",
        "Real-Time Sports Score Tracker",
        "AI-Based Job Interview Preparation Platform",
        "Decentralized Marketplace for Digital Art",
        "Online Interactive Storytelling Platform",
        "AI-Powered Resume and Cover Letter Analyzer",
        "Smart Travel Planner with Budget Tracker",
        "Automated Social Media Content Generator",
        "AI-Based Personalized Learning Portal",
        "Online Customer Support Chatbot",
        "Collaborative Task Management App",
        "Smart Budgeting Tool for Small Businesses",
        "Online Exam and Quiz Platform",
        "AI-Based Social Media Sentiment Analyzer",
        "AI-Powered Automated Website Builder",
        "Real-Time Weather Dashboard with Alerts",
        "Crowdsourced Product Review Platform",
        "Virtual Business Card Generator",
        "AI-Based Smart Email Sorting Tool",
        "Decentralized Job Board for Freelancers",
        "AI-Powered Automated Resume Ranking System",
        "Gamified Learning Platform for Kids",
        "Online Subscription Tracker",
        "Real-Time Crypto Price Tracker",
        "Online Pet Adoption Platform",
        "AI-Powered Personal Assistant Dashboard",
        "Crowdsourced Idea Validation Platform",
        "AI-Based Automated Presentation Generator",
        "Real-Time Language Translator for Websites",
        "Online Community for Book Lovers",
        "AI-Powered AI Art Generator",
        "AI-Based Automated Video Subtitle Generator",
        "Online Smart Meal Planner",
        "Web-Based Personal Health Journal",
        "AI-Powered Fake News Detection Tool",
        "Web-Based Minimalist To-Do List App",
        "AI-Powered Learning Path Generator",
        "Real-Time Traffic and Route Optimization Tool",
        "Decentralized Voting System for Online Polls",
        "Online Therapy and Mental Wellness Platform",
        "Interactive Resume Builder with Portfolio Integration",
        "Smart Home Energy Management Dashboard",
        "AI-Based Automated Social Media Post Scheduler",
        "Web-Based Gamified Workout Challenge Platform",
        "Personalized Podcast Recommendation System",
        "AI-Powered Smart Notes Organizer",
        "Web-Based Secure Digital Signature Generator",
        "AI-Based Automated Stock Market Analysis Tool",
        "Web-Based Open Source AI Model Repository",
        "Web-Based Personal AI Assistant",
        "AI-Powered Career Counseling Chatbot",
        "AI-Based Virtual Study Group Matchmaker",
        "Online Personalized Language Learning Platform",
        "AI-Powered Personal Finance Advisor",
        "Web-Based AI-Powered Search Engine",
        "Online Freelancer Skill Development Tracker",
        "AI-Based Automated Personal Blogging Platform",
        "Web-Based Real-Time Smart Meeting Minutes Generator",
        "AI-Powered Customer Feedback Analysis Tool",
        "Web-Based AI-Powered Document Translator",
        "Online Decentralized File Storage Platform",
        "AI-Powered Product Recommendation Engine",
        "Web-Based Anonymous Social Media Platform",
        "Web-Based Interactive Resume Timeline",
        "AI-Powered Web-Based Legal Document Summarizer",
        "Online Data Visualization Dashboard",
        "AI-Powered Job Skill Assessment Platform",
        "Web-Based Personalized Workout Generator",
        "Real-Time Event Ticketing and Booking System",
        "Web-Based Ethical Hacking Learning Platform",
        "AI-Powered Automated Podcast Creator",
        "Web-Based AI-Powered Smart Virtual Assistant",
        "Decentralized Web-Based Digital Rights Management System",
        "Online Crowdfunding Platform for Social Causes",
        "AI-Powered AI Chatbot for Small Businesses",
        "Web-Based AI-Powered Personal Time Management Assistant",
        "Online Personal Brand Management Dashboard",
        "Web-Based AI-Powered Market Trend Analyzer",
        "Real-Time AI-Powered Resume Feedback Tool",
        "AI-Powered Web-Based Automated Chatbot Generator",
        "Web-Based AI-Powered Personalized Investment Planner",
        "AI-Based Smart Restaurant Menu Recommendation",
        "Web-Based Decentralized Data Ownership Platform",
        "AI-Powered Web-Based Automated Resume Screening Tool",
        "Online AI-Powered Social Media Content Generator",
        "AI-Powered Web-Based Sentiment Analysis Tool",
        "Web-Based Virtual Reality-Based Travel Guide",
        "Online AI-Powered Personal Music Recommendation Engine",
        "Web-Based Smart Gardening Assistant",
        "AI-Powered Web-Based Stock Portfolio Management Tool",
        "Web-Based AI-Powered Smart Interview Coach",
        "Online Web-Based AI-Powered Smart Resume Formatter",
        "AI-Based Smart Contact Management System",
        "Web-Based AI-Powered Emotional Well-Being Tracker",
        "Web-Based Personalized Movie Recommendation System",
        "AI-Powered Web-Based Digital Portfolio Showcase",
        "Web-Based Decentralized Online Education Platform",
        "Online AI-Powered Smart Content Curation Tool",
        "AI-Powered Web-Based Freelance Work Marketplace",
        "Online Web-Based AI-Powered Smart Business Plan Generator",
        "AI-Powered Web-Based Smart Personality Assessment Tool",
        "Web-Based Interactive AI-Powered Storytelling Platform",
        "AI-Powered Web-Based Smart Employee Feedback System",
        "Web-Based AI-Powered Personalized Shopping Assistant",
        "AI-Powered Web-Based Smart Traffic Violation Detection",
        "Web-Based AI-Powered Gamified Fitness App",
        "AI-Powered Web-Based Smart Personalized Learning Assistant",
        "Online AI-Powered Web-Based Real-Time Collaborative Coding Platform",
        "Web-Based AI-Powered Personalized Meditation Assistant",
        "AI-Powered Web-Based Real-Time Smart Language Pronunciation Guide",
        "Web-Based AI-Powered Smart Study Planner",
        "AI-Powered Web-Based Smart Resume and LinkedIn Optimization Tool",
        "Web-Based AI-Powered AI Career Progression Analysis Tool",
        "Online AI-Powered Web-Based Smart Image Colorizer",
        "Web-Based AI-Powered AI-Powered Virtual Art Gallery",
        "Web-Based AI-Powered Smart Personality Development Guide",
        "Online Web-Based AI-Powered Virtual Home Designer",
        "AI-Powered Web-Based Smart Budget Allocation Tool",
        "Web-Based AI-Powered Smart Relationship Compatibility Checker",
        "Online AI-Powered Web-Based Smart Legal Assistant",
        "AI-Powered Web-Based Smart Sentiment-Based Book Recommendation System",
        "Web-Based AI-Powered Personalized Horoscope Generator",
        "Online AI-Powered Web-Based Smart Virtual Wedding Planner",
        "Web-Based AI-Powered Smart Event Planning Assistant",
        "AI-Powered Web-Based Smart Emotional Intelligence Coach",
        "Web-Based AI-Powered Smart Career Roadmap Visualization Tool",
        "AI-Powered Web-Based Smart Automated Data Entry System",
        "Online AI-Powered Web-Based Smart Team Collaboration Hub",
        "Web-Based AI-Powered Smart Nutrition Advisor",
        "Online AI-Powered Web-Based Smart Image Background Remover",
        "AI-Powered Web-Based Smart Task Automation Assistant",
        "Web-Based AI-Powered Smart Resume Video Creator",
        "Online AI-Powered Web-Based Smart Virtual Therapy Room",
        "AI-Powered Web-Based Smart Automated Book Summary Generator",
        "Web-Based AI-Powered Smart Video Editing Assistant",
        "AI-Powered Web-Based Smart AI-Powered Virtual Tutor",
        "Web-Based AI-Powered Smart Digital Art Workshop Platform",
        "AI-Powered Web-Based Smart Emotional Wellness Tracker",
        "Web-Based AI-Powered Smart Custom Avatar Creator",



        "AI-powered Study Assistant",
        "AI Resume Analyzer",
        "AI Chatbot for Mental Health Support",
        "AI-Based Personalized Learning Platform",
        "AI-Powered Code Review Tool",
        "AI-Powered Virtual Career Coach",
        "AI-Based Resume Scoring System",
        "AI for Real-Time Sign Language Translation",
        "AI-Powered Interview Preparation Assistant",
        "AI-Based Financial Advisor for Students",
        "AI-Powered Fake News Detector",
        "AI-Based Automated Recipe Generator",
        "AI-Powered Voice Cloning for Accessibility",
        "AI-Based Image Captioning Tool",
        "AI-Powered Smart Note-Taking Assistant",
        "AI-Based Real-Time Language Translator",
        "AI-Powered Podcast Summarizer",
        "AI-Based Health Risk Prediction System",
        "AI-Powered Diet Recommendation App",
        "AI-Based Music Recommendation for Mood",
        "AI-Powered Resume Builder with Suggestions",
        "AI-Powered Career Path Predictor",
        "AI-Based Time Management Assistant",
        "AI-Powered Personalized Book Recommendation",
        "AI-Powered News Summarization Tool",
        "AI-Based Personalized Fitness Trainer",
        "AI-Powered Smart Meeting Notes Generator",
        "AI-Based Chatbot for Academic Guidance",
        "AI-Powered Email Summarizer",
        "AI-Based Personalized Movie Recommendation",
        "AI-Based Code Debugging Assistant",
        "AI-Powered Virtual Science Experiment Platform",
        "AI-Based Brainstorming Partner",
        "AI-Powered Online Debate Analyzer",
        "AI-Based Online Exam Proctoring System",
        "AI-Powered Language Pronunciation Trainer",
        "AI-Based Personalized Nutrition Planner",
        "AI-Powered Adaptive Learning for Dyslexic Students",
        "AI-Based Career Skill Assessment Tool",
        "AI-Powered Job Interview Simulator",
        "AI-Based Legal Document Summarizer",
        "AI-Powered Auto-Reply System for Emails",
        "AI-Based Online Teaching Assistant",
        "AI-Powered Voice Emotion Detection",
        "AI-Based Stress Management Coach",
        "AI-Powered Smart Resume Formatting Tool",
        "AI-Based Noise Reduction for Online Meetings",
        "AI-Powered Personalized Playlist Generator",
        "AI-Based Automated Customer Service Bot",
        "AI-Powered Fact-Checking Tool for Journalists",
        "AI-Based Medical Symptom Checker",
        "AI-Powered Social Media Sentiment Analyzer",
        "AI-Based Virtual Tutor for Programming",
        "AI-Powered Smart Calendar Assistant",
        "AI-Based Voice-Controlled Task Manager",
        "AI-Powered Website Content Optimizer",
        "AI-Based Virtual Therapist for Anxiety",
        "AI-Powered Emotion-Based Music Player",
        "AI-Based Auto-Transcriber for Lectures",
        "AI-Powered Smart Traffic Management System",
        "AI-Based Weather Impact Predictor",
        "AI-Powered Chatbot for Parenting Advice",
        "AI-Based Personalized Wedding Planner",
        "AI-Powered Online Reputation Management",
        "AI-Based Gamified Learning Platform",
        "AI-Powered Automated Data Entry Assistant",
        "AI-Based Smart Document Scanner",
        "AI-Powered AI Art Generator",
        "AI-Based Personalized Study Roadmap Creator",
        "AI-Powered Travel Itinerary Generator",
        "AI-Based Automated Health Reports Analysis",
        "AI-Powered Remote Team Collaboration Assistant",
        "AI-Based Smart Virtual Business Assistant",
        "AI-Powered Smart Clothing Recommendation System",
        "AI-Based Virtual Museum Guide",
        "AI-Powered Personal Finance Planner",
        "AI-Based AI-Powered Coding Mentor",
        "AI-Powered Predictive Maintenance for Cars",
        "AI-Based Real-Time Stock Market Predictor",
        "AI-Powered Automated Podcast Creator",
        "AI-Based Virtual Reality Storytelling Assistant",
        "AI-Powered Fake Product Review Detector",
        "AI-Based Employee Productivity Tracker",
        "AI-Powered YouTube Video Summary Generator",
        "AI-Based Real-Time Speech Translator",
        "AI-Powered Personalized Workout Routine Generator",
        "AI-Based AI-Powered Mental Health Checkup Tool",
        "AI-Powered AI-Based Home Automation Assistant",
        "AI-Based Emotional Intelligence Trainer",
        "AI-Powered 3D Model Generator",
        "AI-Based Smart Presentation Builder",
        "AI-Powered Automated UX/UI Design Assistant",
        "AI-Based Personalized Content Generator for Creators",
        "AI-Powered AI-Based Dating Advice Bot",
        "AI-Based Personalized Stock Investment Guide",
        "AI-Powered AI-Powered Ethical Hacking Assistant",
        "AI-Based Automated Performance Review Analyzer",
        "AI-Powered Smart Home Energy Optimization",
        "AI-Based AI-Powered Startup Pitch Generator",
        "AI-Powered AI-Based Resume Cover Letter Writer",
        "AI-Based AI-Powered Digital Twin for Business",
        "AI-Powered AI-Based Legal Chatbot",
        "AI-Based AI-Powered Video Game Level Generator",
        "AI-Powered AI-Based Personal AI Assistant",
        "AI-Based AI-Powered Podcast Voice Enhancer",
        "AI-Powered AI-Based AI Ethics Evaluator",
        "AI-Based AI-Powered Political Bias Detector",
        "AI-Powered AI-Based Smart Farming Assistant",
        "AI-Based AI-Powered 3D Avatar Creator",
        "AI-Powered AI-Based Personalized Virtual Therapist",
        "AI-Based AI-Powered Online Privacy Protector",
        "AI-Powered AI-Based Smart Parking Assistant",
        "AI-Based AI-Powered Real-Time Virtual Interviewer",
        "AI-Powered AI-Based Automated Book Summarizer",
        "AI-Based AI-Powered Personalized Marketing Assistant",
        "AI-Powered AI-Based AI-Powered Automated Subtitles Generator",
        "AI-Based AI-Powered Student Grade Prediction System",
        "AI-Powered AI-Based AI-Powered Automated Report Writer",
        "AI-Based AI-Powered Custom Recipe Generator",
        "AI-Powered AI-Based AI-Powered Fashion Trend Predictor",
        "AI-Based AI-Powered AI-Powered Speech Therapy Assistant",
        "AI-Powered AI-Based Personalized Travel Planner"
    ]



};



function generateIdea() {
    let category = document.getElementById("category").value;
    let selectedIdeas = ideas[category];
    let randomIndex = Math.floor(Math.random() * selectedIdeas.length);
    document.getElementById("idea").innerText = selectedIdeas[randomIndex];
}
